<div class="jumbotron">
    <h1><?php echo $this->translate('Google OAuth2 Guestbook Demo') ?></h1>
    <p><?php echo $this->translate('This is a demo of using the Google OAuth2 authentication mechanism available to the Google API (and other providers) to access information about your google.com account. You can find the source code for this demo by clicking the link below.') ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/coogle/google-oauth2" target="_blank"><?php echo $this->translate('Fork this Demo on GitHub') ?> &raquo;</a></p>
</div>
<?php $showSave = $this->oAuthToken->isValid() || (APPLICATION_ENV == 'development'); ?>
<div class="row">
	<div class="col-xs-12 col-sm-6 col-lg-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"><?php echo $this->translate("Submit to our Guestbook"); ?></h3>
			</div>
			<div class="panel-body">
				<form action="/application/index/post" method="POST">
					<input type="text" <?php echo $showSave ? '' : 'disabled="disabled"' ?> name="message" size="80" placeholder="Type your message here."/>
					<?php if($showSave): ?>
					<input type="submit" value="Save"/>
					<?php else: ?>
					<a href="/oauth2/callback"><img height="30" src="https://developers.google.com/+/images/branding/sign-in-buttons/White-signin_Medium_base_44dp.png" alt="Sign in with Google"/></a>
					<?php endif; ?>
				</form>
				</p>
			</div>
		</div>
	</div>
</div>
<div class="row">
<?php foreach($this->pagedEntries as $entry): ?>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">From <?php echo $this->escapehtml($entry->getName())?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->escapehtml($entry->getMessage())?></p>
            </div>
        </div>
    </div>
<?php endforeach;?>
</div>
<center>
 <?php
 echo $this->paginationControl(
     $this->pagedEntries,
     'sliding',
     array('partial/paginator.phtml', 'Guestbook'),
     array(
         'route' => 'home'
     )
 );
 ?>
</center>